spring:
  application:
    name: road-transformer
  datasource:
    url: jdbc:mysql://roadtransformer.cvk0oth4xubz.us-east-1.rds.amazonaws.com:3306/roadtransformer?useSSL=false
    username: adminuser
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 30MB
aws:
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}
  s3:
    bucketName: roadtransformer
maps:
  apiKey: AIzaSyAoDmpKV7ONNygXJ9XWiZPimb_oJOHYj9s
  reverse_geocoding_api: 'https://maps.googleapis.com/maps/api/geocode/json?key=${maps.apiKey}&latlng='
email-notifications:
  alert-confidence: 70 # if confidence is less than 70, send email
  

